# Generated by Django 4.0.4 on 2022-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='description',
        ),
        migrations.RemoveField(
            model_name='api',
            name='done',
        ),
        migrations.RemoveField(
            model_name='api',
            name='title',
        ),
        migrations.AddField(
            model_name='api',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='api',
            name='format',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='api',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='api',
            name='scheduler',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='api',
            name='time',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='api',
            name='weekday',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='api',
            name='date',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
