export const schedulerTypes = {
  SET_CURRENT_SCHEDULER: "SET_CURRENT_SCHEDULER",
  SET_CURRENT_DATE: "SET_CURRENT_DATE",
  SET_CURRENT_DAY: "SET_CURRENT_DAY",
  SET_CURRENT_TIME: "SET_CURRENT_TIME",
  DELETE_DATA: "DELETE_DATA",
};
